name: AceDeck
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  ficonsax: ^0.0.3
  fl_chart: ^0.64.0
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  hidden_drawer_menu: ^3.0.1
  lottie: ^2.7.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - images/
  uses-material-design: true

  fonts:
    - family: BlackOpsOne
      fonts:
        - asset: fonts/BlackOpsOne-Regular.ttf
          weight: 500
